---
- hosts: all
  user: hoang
  roles:
    - nfs-install
  tags:
    - nfs-install

- hosts: all
  user: hoang
  roles:
    - passwd-rootlogin
    - k8s-preinstall
  tags:
    - pre-install

- hosts: all
  user: hoang
  roles:
    - passwd-rootlogin
    - k8s-preinstall
  tags:
    - pre-install

- hosts: all
  user: hoang
  roles:
    - k8s-install
  tags:
    - install
...