---

- name: clean source
  file: 
    path: /var/lib/apt/lists/*
    state: absent

- name: apt-get clean & update & upgrade
  apt:
    autoclean: yes
    update_cache: yes
    upgrade: yes

- name: change hosts file
  copy: 
    src: "{{ item.src }}" 
    dest: "{{ item.dest }}" 
  with_items:
  - { src: '../files/hosts', dest: '/etc' }
  - { src: '../files/k8s.conf', dest: '/etc/sysctl.d' }


- name: disable swap 
  shell: swapoff -a
  when: disable_swap == 1

- name: disable swap in fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

# - name: reboot
#   reboot:

- name: enable br_netfilter module
  modprobe: 
    name: br_netfilter
    state: present
  when: disable_swap == 1

- name: enable overlay module
  modprobe: 
    name: overlay
    state: present
  when: disable_swap == 1
  notify: "sysctl --system"
...