---
nfs_exports: [ "/nfs *(rw,sync,no_subtree_check)" ]

nfs_rpcbind_state: started
nfs_rpcbind_enabled: true

fstab: "{{ nfs_server }}:/nfs /nfs/ nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0"
nfs_server: 192.168.75.128