---
- name: Create share directory
  file:  
    path: "{{ item.strip().split()[0] }}"
    state: directory
  with_items: "{{ nfs_exports }}"

- name: "Create partitions on devices"    
  block:
    - name: create partition from block devices
      parted:
        device: /dev/sdb
        number: 1
        flags: [ lvm ]
        state: present
        part_end: "100%"

    - name: format the partition
      filesystem:
        fstype: ext4
        dev: /dev/sdb1

    - name: mount new partition to /nfs
      mount:
        fstype: ext4
        src: /dev/sdb1
        path: /nfs
        state: mounted

  when: inventory_hostname in groups['k8s-master']
