---

- hosts: all
  user: hoang
  roles:
    - passwd-rootlogin
    - k8s-preinstall
  tags:
    - pre-install

- hosts: all
  user: hoang
  roles:
    - k8s-install
  tags:
    - install

# - hosts: k8s-master
#   user: hoang
#   roles:
#     - minikube-install
#   tags:
#     - minikube-install
...