---
- name: reload nfs
  command: 'service nfs-kernel-server restart'

- name: reload nfs-common
  shell: |
    rm /lib/systemd/system/nfs-common.service
    systemctl daemon-reload
    service nfs-common start