---
- name: reload nfs
  shell: |
    service nfs-kernel-server restart
    exportfs -rav

- name: reload nfs-common
  shell: |
    rm /lib/systemd/system/nfs-common.service
    systemctl daemon-reload
    service nfs-common start